# Welcome to Colab Enterprise <img src="https://lh3.googleusercontent.com/UiNooY4LUgW_oTvpsNhPpQzsstV5W8F7rYgxgGBD85cWJoLmrOzhVs_ksK_vgx40SHs7jCqkTkCk=e14-rj-sc0xffffff-h130-w32" alt="Vertex AI logo">

Connect to a Runtime and begin!

<div class="markdown-google-sans">

## **Getting started**
</div>

The document you are reading is not a static web page, but an interactive environment called a **Colab notebook** that lets you write and execute code.

For example, the code cell below uses **numpy** to generate some random data, and uses **matplotlib** to visualize it. To edit the code, just click the cell and start editing.

In [12]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

## **Columns in the Iris Dataset:**
**Sepal Length (cm):** This is the length of the sepal (one of the two parts of the flower's calyx) in centimeters.

**Sepal Width (cm):** This is the width of the sepal in centimeters.

**Petal Length (cm):** This is the length of the petal (the part of a flower that is often colorful and has a scent) in centimeters.

**Petal Width (cm):** This is the width of the petal in centimeters.

**Species:** This is the species of the iris plant.
The dataset includes three species:

Iris setosa

Iris versicolor

Iris virginica

## **Characteristics of the Dataset:**

**Number of Instances:** 150 (50 in each of three classes)

**Type of Attributes:** Real, positive numbers, in centimeters

**Missing Attribute Values:** None

In [13]:
# Load and prepare the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target
y = to_categorical(y)  # Convert labels to one-hot encoding

# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [14]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [16]:
# Create a simple neural network model
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))  # 3 output neurons for 3 classes

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=150, batch_size=10, verbose=1)

Epoch 1/150
11/11 [==============================] - 1s 2ms/step - loss: 1.2551 - accuracy: 0.2095
Epoch 2/150
11/11 [==============================] - 0s 2ms/step - loss: 1.2012 - accuracy: 0.2000
Epoch 3/150
11/11 [==============================] - 0s 2ms/step - loss: 1.1598 - accuracy: 0.2190
Epoch 4/150
11/11 [==============================] - 0s 2ms/step - loss: 1.1251 - accuracy: 0.2000
Epoch 5/150
11/11 [==============================] - 0s 2ms/step - loss: 1.0963 - accuracy: 0.1524
Epoch 6/150
11/11 [==============================] - 0s 2ms/step - loss: 1.0714 - accuracy: 0.1143
Epoch 7/150
11/11 [==============================] - 0s 2ms/step - loss: 1.0517 - accuracy: 0.1048
Epoch 8/150
11/11 [==============================] - 0s 2ms/step - loss: 1.0301 - accuracy: 0.1429
Epoch 9/150
11/11 [==============================] - 0s 2ms/step - loss: 1.0127 - accuracy: 0.2952
Epoch 10/150
11/11 [==============================] - 0s 2ms/step - loss: 0.9938 - accuracy: 0.3143
Epoch 11/

In [17]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Accuracy: {accuracy:.2f}')

2/2 [==============================] - 0s 8ms/step - loss: 0.1541 - accuracy: 1.0000
Accuracy: 1.00
